claeis/ili2db

build-ili2gpkg.xml
build-ili2pg.xml

Added a fatjar target in the ili2pg and ili2gpkg build files.

fatjar target for ili2pg and ili2gpkg

---

ili2pg/src/ch/ehi/ili2pg/Version.properties
src/ch/ehi/ili2db/AbstractMain.java
src/ch/ehi/ili2db/base/DbNames.java
src/ch/ehi/ili2db/base/Ili2db.java
src/ch/ehi/ili2db/gui/Config.java

Create additional ili-model information tables for issue (claeis/ili2db#63)

Create additional ili-model information tables for issue

---

src/ch/ehi/ili2db/dbmetainfo/DbExtMetaInfo.java
src/ch/ehi/ili2db/fromili/FromIliRecordConverter.java

More info for --createMetaInfo option.
References #63

Add MTEXT info to t_ili2db_column_prop

---

src/ch/ehi/ili2db/base/DbNames.java
src/ch/ehi/ili2db/fromili/TransferFromIli.java

+ New column 'description' for enum tables
Fix #89

Use ilidoc as enum value description

---

src/ch/ehi/ili2db/dbmetainfo/DbExtMetaInfo.java
src/ch/ehi/ili2db/fromili/FromIliRecordConverter.java
src/ch/ehi/ili2db/fromili/TransferFromIli.java

Read/use @ili2db.dispName for tables and columns

---

ili2mssql/src/ch/ehi/ili2mssql/MsSqlMain.java
ili2mssql/src/ch/ehi/ili2mssql/sqlgen/GeneratorMsSql.java

Fix issue 123 ili2mssql: support UUID

---

ili2mssql/src/ch/ehi/ili2mssql/MsSqlCustomStrategy.java

Issue #203 
ili2mssql: Add prePreScript and postPostScript to enable and disable foreign keys.

Added prePreScript and postPostScript to enable and disable foreign keys

---

src/ch/ehi/ili2db/dbmetainfo/DbExtMetaInfo.java
src/ch/ehi/ili2db/fromili/FromIliRecordConverter.java

Added FK meta info to T_ILI2DB_COLUMN_PROP

Added FK meta info to T_ILI2DB_COLUMN_PROP

---

ili2ora/src/ch/ehi/ili2ora/converter/OracleSpatialColumnConverter.java
ili2ora/src/ch/ehi/ili2ora/sqlgen/GeneratorOracleSpatial.java

- Added ILI2ORA_SDO_GEOMETRY  function that wraps SDO_GEOMETRY Constructor because that constructor fails when geometry is null
- Changed SDO_UTIL.FROM_WKBGEOMETRY function for SDO_GEOMETRY Constructor (ILI2ORA_SDO_GEOMETRY) for srid support

ili2ora: Fixed. Added PLSQL function wrapper to SDO_GEOMETRY

---

ili2mssql/src/ch/ehi/ili2mssql/converter/MsSqlColumnConverter.java

Added to MssqlColumn converter:
- getInsertValueWrapperMultiCoord
- getSelectValueWrapperMultiCoord
- getSelectValueWrapperMultiPolyline
- getInsertValueWrapperMultiPolyline

ili2mssql: Added multicoord and multipolyline support

---

ili2ora/src/ch/ehi/ili2ora/OraMain.java
ili2ora/src/ch/ehi/ili2ora/OraSequenceBasedIdGen.java
ili2ora/src/ch/ehi/ili2ora/OracleCustomStrategy.java
ili2ora/src/ch/ehi/ili2ora/converter/OracleSpatialColumnConverter.java
ili2ora/src/ch/ehi/ili2ora/sqlgen/GeneratorOracleSpatial.java

- Remove duplicated code
- Rename variables and constants

ili2ora: code refactoring

---

ili2pg/test/java/ch/ehi/ili2db/MultisurfaceTest.java
test/data/MultiSurface/MultisurfaceEmpty.sql

Add empty multisurface test

---

ili2mssql/src/ch/ehi/ili2mssql/MsSqlCustomStrategy.java
ili2mssql/src/ch/ehi/ili2mssql/MsSqlMain.java
ili2mssql/src/ch/ehi/ili2mssql/MsSqlSequenceBasedIdGen.java
ili2mssql/src/ch/ehi/ili2mssql/converter/MsSqlColumnConverter.java
ili2mssql/src/ch/ehi/ili2mssql/sqlgen/GeneratorMsSql.java
ili2mssql/test/java/ch/ehi/ili2mssql/Enum23Test.java
ili2mssql/test/java/ch/ehi/ili2mssql/MsSqlTestSetup.java
ili2mssql/test/java/ch/ehi/ili2mssql/SimpleMsSqlTest.java
ili2mssql/test/java/ch/ehi/ili2mssql/test_utils/TestUtils.java

- Remove duplicated code
- Move duplicated code to new private methods
- Rename variables, constants
- Remove unnecessary overridden methods

ili2mssql: code refactoring

---

ili2mssql/src/ch/ehi/ili2mssql/converter/MsSqlColumnConverter.java

Fix 3D geometries support for SQL Server (see claeis/iox-ili#88)

Fix 3D geometries support for SQL Server

---

build.gradle

Support for Windows sspi login
Fixes #369

Add waffle-jna 1.9.1 as ili2pg dependency

---

build.gradle

Adds support for postgres 13
Fixes #371

Bump org.postgresql to v42.2.18

---

ili2fgdb/src/ch/ehi/ili2fgdb/FgdbMain.java
ili2gpkg/src/ch/ehi/ili2gpkg/GpkgMain.java
ili2h2gis/src/ch/ehi/ili2h2gis/H2gisMain.java
ili2mssql/src/ch/ehi/ili2mssql/MsSqlMain.java
ili2mysql/src/ch/ehi/ili2mysql/MysqlMain.java
ili2ora/src/ch/ehi/ili2ora/OraMain.java
ili2pg/src/ch/ehi/ili2pg/PgMain.java
src/ch/ehi/ili2db/AbstractMain.java

Add support for --option=booleanValue

---

ili2gpkg/test/java/ch/ehi/ili2gpkg/MultiCoord24Test.java
ili2pg/test/java/ch/ehi/ili2pg/MultiCoord24Test.java
src/ch/ehi/ili2db/converter/AbstractRecordConverter.java
src/ch/ehi/ili2db/fromili/FromIliRecordConverter.java
src/ch/ehi/ili2db/fromili/TransferFromIli.java
src/ch/ehi/ili2db/fromxtf/FromXtfRecordConverter.java
src/ch/ehi/ili2db/mapping/Viewable2TableMapper.java
src/ch/ehi/ili2db/toxtf/ToXtfRecordConverter.java
test/data/MultiCoord24/MultiCoord24.ili
test/data/MultiCoord24/MultiCoord24.xtf
test/java/ch/ehi/ili2db/MultiCoord24Test.java

Add MULTICOORD support

---

ili2gpkg/src/ch/ehi/ili2gpkg/init.sql

gpkg: fix superfluous blank in default column value

---

build.gradle
src/ch/ehi/ili2db/fromili/FromIliRecordConverter.java

REQ: Fix of [ili2db: Unique constraints are not generated #493](https://github.com/claeis/ili2db/issues/493)
REQ: [ili2c: Eindeutigkeitsbedingungen auf den einzelnen Transfer#90](https://github.com/claeis/ili2c/issues/90)
REF: [ili24: Eindeutigkeitsbedingungen auf den einzelnen Transfer#518](https://github.com/claeis/ili2db/issues/518)

Eindeutigkeitsbedingungen auf den einzelnen Transfer

---

src/ch/ehi/ili2db/fromili/TransferFromIli.java
test/data/Enum23/Enum23.ili

References: https://github.com/claeis/ili2db/issues/543

Handle boolean domains when option --createEnumTabs is set
